name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Connect to VPS and deploy
        run: |
          ssh ${{ secrets.SERVER_IP }} "
            cd /app;
            git pull origin main;
            docker-compose down;
            docker-compose up -d
          "
