name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo ${{ github.repository }}
            REPO_URL="git@github.com:${{ github.repository }}.git"
            APP_DIR="/app"

            if [ -d "$APP_DIR/.git" ]; then
              echo "Git repo found, pulling latest changes..."
              cd "$APP_DIR" && git pull origin main
            else
              echo "Git repo not found, cloning fresh..."
              mkdir -p "$APP_DIR"
              git clone "$REPO_URL" "$APP_DIR"
            fi

            cd "$APP_DIR"
            docker-compose down
            docker-compose up -d --build
